language: go
sudo: false
go:
  - 1.11
env:
  global:
    - GO111MODULE=on
  matrix:
    - TMUX_VERSION=master
    - TMUX_VERSION=2.8
    - TMUX_VERSION=2.7
    - TMUX_VERSION=2.6
    - TMUX_VERSION=2.5
    - TMUX_VERSION=2.4
    - TMUX_VERSION=2.3
    - TMUX_VERSION=2.3
    - TMUX_VERSION=2.2
    - TMUX_VERSION=2.1
    - TMUX_VERSION=2.0

addons:
  apt:
    packages:
      - libevent-dev

before_script:
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure --prefix=$HOME/tmux && make && make install
  - export PATH=$HOME/tmux/bin:$PATH
  - cd ..
  - 'echo "set -g base-index 1\nset-option -g renumber-windows on" > ~/.tmux.conf'
  - tmux -V

script:
  - export PATH=$HOME/tmux/bin:$PATH
  - make test
